### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by itsermin** [dhedge/buyback-contract#7]
### L1Comptroller

> L123 // Question: Should this be allowed to be called only once?

I think it's ok to be called more than once if needed. I don't see the scenario but doesn't hurt (low cost optionality)

> // Question: Rug pull protection?

Not sure on the question. I think we should be able to withdraw in case of emergency

### L2Comptroller

> L280 // Question: Should we change the name of the function to "updateAndTransfer" instead?

Up to you

> L311 // QUESTION: Does this event emission makes sense to be included?

Don't feel strongly, up to you

> L373 // Question: Should this be allowed to be called only once?
> // Question: Do we really need to emit this? Ideally, this function would be used only once.

I think it's ok to keep

> // Question: Rug pull protection?

Same thoughts as the L1 question

**Comment by rashtrakoff** [comment]
@itsermin , this can be closed now.
